apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: jdk
  template:
    metadata:
      labels:
        app: jdk
    spec:
      containers:
      - name: jdk
        image: nginx
        volumeMounts:
        - name: jmx-volume
          mountPath: "/fayfa"
        ports:
        - containerPort: 8080
      initContainers:
      - name: jmx-exporter
        image: fayfa/jmx:v3
        volumeMounts:
        - mountPath: /app
          name: jmx-volume
      volumes:
      - name: jmx-volume
        emptyDir: {}



        